platform :ios, '9.0'

target 'Uptempo' do
  use_frameworks!

  pod 'Fusuma', :git => 'https://github.com/m3dh/Fusuma.git'
  pod 'Alamofire', '~> 4.5'
  target 'UptempoTests' do
    inherit! :search_paths
  end

end
